import CMainBar from './CMainBar/CMainBar.vue'
import CMain from './CMain/CMain.vue'
import CButton from './CButton/CButton.vue'
import CCard from './CCard/CCard.vue'
import CCardTitle from './CCard/CCardTitle.vue'
import CCardContent from './CCard/CCardContent.vue'
import CContainer from './CContainer/CContainer.vue'
import CText from './CText/CText.vue'
import CAlert from './CAlert/CAlert.vue'
import CIcon from './CIcon/CIcon.vue'
import CInput from './CInput/CInput.vue'
import CForm from './CForm/CForm.vue'
import CFlex from './CFlex/CFlex.vue'

export default {CMainBar,CMain, CButton, CCard, CContainer, CCardTitle, CCardContent, CText, CAlert, CIcon, CInput, CForm, CFlex}